---
title: "day2"
author: "Rachel Ganly"
date: "12/2/2021"
output: html_document
---

Set-up

```{r, include=FALSE}
# Clear workspace
rm(list = ls())

# Load packages
library(tidyverse)
library(pillar)


```

Get data

```{r}
filepath<-paste0("/Users/rachelganly/OneDrive - HKUST Connect/HKUST/R Files/GitHub/AdventOfCode","/input/day2.txt")
data<-read.csv(file = filepath,header = FALSE)
```


Part 1 

```{r, echo=FALSE}
glimpse(data)

day2<-data%>%
rename(Movement=V1)%>%
  mutate(Movement=as.character(Movement))%>%
  separate(col=Movement,into=c("Direction","Value"),sep=" ", remove=FALSE)%>%
  mutate(x=ifelse(str_detect(string = Direction,pattern = "forward"),as.numeric(Value),0),
         y=ifelse(str_detect(string = Direction,pattern = "down"),as.numeric(Value),
 ifelse(str_detect(string = Direction,pattern = "up"),as.numeric(Value)*-1,0)))

total<-day2%>%summarize(sum.x=sum(x),sum.y=sum(y))

total[1]*total[2]
  
                   
```


Part 2

```{r}

  aim<-0
  n<-nrow(day2)
  aim_total<-c(1:n)
  
for (i in 1:n){
  aim<-aim+day2$y[i]
  aim_total[i]<-aim
}
  
day2<-day2%>%bind_cols(day2,aim_total, .name_repair = "universal")%>%
  select(Movement...1,Direction...2,Value...3,x...4,y...5,...11)%>%
  rename(Movement=Movement...1,
         Direction=Direction...2,
         Value=Value...3,
         x=x...4,
         y=y...5,
         aim=...11)

  depth<-0
  n<-nrow(day2)
  depth_total<-c(1:n)
  
for (i in 1:n){
  depth<-depth+(day2$aim[i]*day2$x[i])
  depth_total[i]<-depth
}
  
 day2<-day2%>%bind_cols(day2,depth_total, .name_repair = "universal")
 
 
horizontal<-sum(day2$x...4) 
answer<-horizontal*depth



```